domains:
- domain: im.mutable.cc
  type: PRIMARY
- domain: mutable.cc
  type: ALIAS

name: mutable-cc-lektor
region: nyc

static_sites:
- build_command: make WEBSITE=mutable.cc lektor-build
  catchall_document: 404.html
  environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: peterwwillis/www.mutable.cc
  name: www-mutable-cc-htdocs
  routes:
    - path: /
  dockerfile_path: Dockerfile
  output_dir: /app/mutable.cc/public
