name: "Deploy site"

concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - 'main'
  workflow_dispatch:
    # Allow manually running workflow
  schedule:
    - cron: '23 2 * * *'

env:
  DEPLOY: >-
    ${{
      github.event_name != 'pull_request'
      && github.ref == 'refs/heads/main'
    }}
  OUTPUT: _html

jobs:

  build:
    name: Build lektor website and move files to gh-pages branch

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}


    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build site with Lektor
        uses: ./.github/actions/lektor
        with:
          makearg: lektor-build

      #- name: Check for broken internal links
      #  uses: wjdp/htmltest-action@master
      #  with:
      #    path: "lektor/${{ env.OUTPUT }}"
      #    config: .htmltest.yml
      #    skip_external: true
      #    log_level: 1

#      - name: Deploy lektor website to gh-pages
#        if: env.DEPLOY == 'true'
#        uses: ./.github/actions/lektor
#        with:
#          makearg: lektor-deploy
#          deploy_username: "peterwwillis"
#          deploy_password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "lektor/${{ env.OUTPUT }}"


  deploy:
    name: Deploy lektor-built site to GitHub Pages
    needs: build

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

