name: "Deploy site"

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - 'main'
  workflow_dispatch:
    # Allow manually running workflow
  schedule:
    - cron: '23 2 * * *'

env:
  DEPLOY: >-
    ${{
      github.event_name != 'pull_request'
      && github.ref == 'refs/heads/main'
    }}
  OUTPUT: _html

jobs:
  deploy:
    name: Deploy lektor website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout

      - name: Build site with Lektor
        uses: ./.github/actions/lektor
        with:
          makearg: lektor-build

      - name: Check for broken internal links
        uses: wjdp/htmltest-action@master
        with:
          path: "lektor/${{ env.OUTPUT }}"
          config: .htmltest.yml
          skip_external: true
          log_level: 1

      - name: Deploy lektor website
        if: env.DEPLOY == 'true'
        uses: ./.github/actions/lektor
        with:
          makearg: lektor-deploy
          deploy_username: "peterwwillis"
          deploy_password: "${{ secrets.GITHUB_TOKEN }}"

