name: "Deploy site"

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - 'main'
  workflow_dispatch:
    # Allow manually running workflow
  schedule:
    - cron: '23 2 * * *'

env:
  DEPLOY: >-
    ${{
    github.event_name != 'pull_request'
    &&
    github.ref == 'refs/heads/master'
    }}
  OUTPUT: _html

jobs:
  build:
    name: Build lektor website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: change directory to mutable.cc
        run: cd mutable.cc

      - name: Install Lektor
        run: |
          python -m pip install lektor

      - name: Build lektor website
        run: lektor build -O '${{ env.OUTPUT }}'

      - name: Check for broken internal links
        uses: wjdp/htmltest-action@master
        with:
          path: ${{ env.OUTPUT }}
          config: .htmltest.yml
          skip_external: true
          log_level: 1

      - name: Deploy lektor website
        if: env.DEPLOY == 'true'
        run: lektor deploy -O '${{ env.OUTPUT }}' ghpages-https
        env:
          LEKTOR_DEPLOY_USERNAME: peterwwillis
          LEKTOR_DEPLOY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
